# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Chuck Langford

description: Stylish Jekyll Theme
author:
  name: Chuck Langford
  email: field.email@gmail.com
  github: ChuckLangford
  #twitter: dbtek
  #pinterest: asd123
  linkedin: chucklangford
  bio: Thoughts from a software dev working with the .NET and MEAN stacks.
  resume: true
  email_md5: 0ab827d396485b42425e5db32283998e

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
